version: '3.7'
services:
  back-end:
    build:
      context: .
      target: 'develop-stage'
    ports:
      - 80:80
    volumes:
      - './app/:/app'
    environment:
      - LOG_LEVEL=info
      - RELOAD=true
    # command: /bin/sh -c "/start-reload.sh" # For production, this line should be removed (no need for hot reload)

  init-db:
    build:
      context: .
      target: 'develop-stage'
    depends_on:
      - back-end
    command: python database.py
